### PR TITLE
Brand-new tutorial

### PR DESCRIPTION
**Pull request by brusherru**
It completely closes https://github.com/xodio/xod/issues/1631

### CODE REVIEW

**Comment by nkrkv** [comment]
Please, target toward the `next` branch

**Comment by brusherru** [comment]
Updated with latest changes in the new tutorial project.

**Comment by nkrkv** [comment]
`108-text-lcd` has circuit partially invisible (external parts ignored?)

**Comment by brusherru** [comment]
@nkrkv fixed.

**Pull request merged**
