### PR TITLE
Translate main doc page and adapted .yaml

### PR DESCRIPTION
**Pull request by UshakovMaksim**
Добавил локализованные строки в .yaml для разных языков

### CODE REVIEW

**Comment by UshakovMaksim** [comment]
Перенёс новый проект в витрину вручную.

**Comment by evgenykochetkov** [comment]
I agree with @nkrkv. The current solution won't scale at all.

**Comment by UshakovMaksim** [comment]
Agree with all you.

**Comment by nkrkv** [comment]
So, Maxim, I think we should demonstrate an example of this method. I can’t promise we’ll find spare time immediately, but I’ll try to arrange the improvement.

**Comment by UshakovMaksim** [comment]
Конечно, буду рад любой помощи. Сегодня у меня не сильно много свободного времени, поэтому долго отвечаю. С Handlebars я первый раз столкнулся на этом проекте.

**Comment by UshakovMaksim** [comment]
Hi guys! Can you review my last commit? Is I doing fallback rules right?

**Comment by nkrkv** [comment]
Hello!

Yes, it’s the right direction. Looks like it will work. :+1: 

This is a big changeset. Can we put changes in the `./guide/` index aside for a while? So that we can verify everything works fine on the docs index page (including the showcase). Then we can apply the same technique to other places.

BTW, do you know that curly braces are optional in YAML:

```yaml
title: {
  en: Hot Dog
  ru: Сосиска в тесте
}
```

is the same as:


```yaml
title:
  en: Hot Dog
  ru: Сосиска в тесте
```

The latter is preferable as it gives fewer chances for errors like unmatched braces.

**Comment by UshakovMaksim** [comment]
Removed curly braces, deleted guide and reference translation.

**Pull request closed without merging**
